def arabalar():

    print("╔════════════════════════════════════════╗")
    print("║ ARABA MARKALARI                        ║")
    print("║                                        ║")
    print("║ 1. VOLKSWAGEN                          ║")
    print("║ 2. TOYOTA                              ║")
    print("║ 3. FIAT                                ║")
    print("║ 4. RENAULT                             ║")
    print("║ 5. OPEL                                ║")
    print("║                                        ║")    
    print("║    SEÇİMİNİZ?                          ║")
    print("╚════════════════════════════════════════╝")
    secim = input()
    if secim == "1" :
            print("Volkswagen grubu Alman otomobil üretici grubu. Yolcu ve ticari araçlar, motosikletler")            
            print("motorlar ve turbo makine imalatı tasarlar, üretir ve dağıtır. Ayrıca finansman, kiralama")
            print("ve filo yönetimi dahil ilgili hizmetler sunar. 2017, 2018 ve 2019'da 10.9 milyon araç satarak,")
            print("dünyanın en büyük otomobil üreticisi oldu. Yirmi yılı aşkın bir süredir Avrupa'daki en büyük")
            print("pazar payını korumuştur. Dünyanın en büyük şirketlerinin 2018 Fortune Global 500 listesinde")
            print("yedinci sırada yer aldı. Volkswagen AG, Porsche SE'nin %52,2 hissesini satın almıştır.")
            print("Volkswagen ayrıca Çin'de iki büyük ortak girişime sahiptir (FAW-Volkswagen ve SAIC Volkswagen).")
            print("Yaklaşık 150 ülkede faaliyet gösteren şirket, 27 ülkede 100 üretim tesisi işletiyor.")
            input()
    elif secim == "2" :
            print("Toyota Motor Corporation, değişen alanlarda üretim yapan ve büyük bir model yelpazesine sahip olan")            
            print("2016 verilerine göre dünyanın en büyük otomotiv şirketidir. 2008 yılı itibarıyla dünyanın en büyük")
            print("otomobil üreticisidir. 77 yıldır bu unvana sahip olan General Motors'tan bu unvanı ele geçirmeyi")
            print("başarmıştır. Japonya dışında, dünyanın birçok yerinde üretim hacmine göre dünyanın en büyük otomotiv")
            print("üreticileri arasında Toyota fabrikaları vardır. Şirket Arjantin, Belçika, Brezilya, Kanada, Kolombiya,")
            print("Çek Cumhuriyeti, Fransa, Endonezya, Meksika, Filipinler, Polonya, Rusya, Güney Afrika, Tayland,")
            print("Türkiye, Birleşik Krallık, Amerika Birleşik Devletleri ve Venezuela'da araç montajı yapmaktadır.")
            print("Ayrıca şirketin Çin, Fransa, Hindistan, Malezya, Pakistan, Tayvan, Amerika Birleşik Devletleri ve")
            print("Vietnam'da ortak girişim, lisanslı veya sözleşmeli fabrikaları vardır.")
            input()
    elif secim == "3" :
            print("Fiat S.p.A. (Fiat Grubu olarak da bilinir) otomobil üreticisi, finansal ve endüstriyel grup.")            
            print("11 Temmuz 1899'da Giovanni Agnelli Tarafından Torino'da kurulmuştur. İsmini Fabbrica Italiana")
            print("Automobili Torino kelimelerinin baş harflerinden almıştır. Bünyesinde Lancia, Alfa Romeo, Maserati")
            print("Chrysler, Dodge, Jeep, Yamaha Motor Company, Iveco, Ferrari gibi markaları barındırmaktadır.")
            print("Yani bu markaların bir anlamda sahibidir. Dünyanın en büyük otomobil ve endüstriyel grupları")
            print("arasında yer alır.")
            input()
    elif secim == "4" :
            print("Renault S.A., Fransız araç üreticisi. Otomobil, kamyon, traktör, tank, tren, uçak,")            
            print("motosiklet, bisiklet, otobüs gibi birçok farklı türde araç üretmektedir. Türkiye'de")
            print("Bursa'da kurulu bulunan Oyak-Renault ortaklığı (%51) ile yatırımı vardır. Ayrıca Nissan")
            print("otomobil markasının motorlarını üretmektedir. Ayrıca yan kuruluşları arasında Rumen araba")
            print("markası Dacia da bulunur. 2016'nın sonu itibarıyla Renault Nissan ortaklığına Mitsubishi")
            print("de dahil olmuştur.")
            input()
    elif secim == "5" :
            print("Opel Automobile GmbH veya kısaca Opel, Alman otomobil üreticisidir. Opel 1929'dan")            
            print("2017'ye kadar, Amerikan otomobil üreticisi General Motors'a aitti. General Motors'dan ")
            print("ayrılan Opel, 2017'de Group PSA bünyesine geçti. 16 Ocak 2021'de Groupe PSA ve")
            print("Fiat Chrysler Automobiles'ın birleşimi ile meydana gelen Stellantis otomotiv şirketine")
            print("katıldı. Opel araçları Birleşik Krallık'ta Vauxhall markası altında satılmaktadır.")
            print("Bazı Opel araçları, Avustralya'da Holden markası altında, Kuzey Amerika ve Çin'de ise")
            print("Buick markası altında üretilmektedir.")
            input()
