print("1. ve 2. sayı toplanıp, 3. sayı ile carpilacak")
a = float(input("1.degeri giriniz:"))
b = float(input("2. değeri giriniz:"))
c = float(input("3. değeri giriniz:"))
hesap = ((a+b)*c)
print("sonuc:",hesap)
input()