print(" Merhaba")
print(" Ertan","Öner")
print(" Adı:Ertan Öner \n Sınıfı:5A \n Numara:451")
print("\n")
print(" Korkma! Sönmez bu şafaklarda yüzen al sancak.")   
print(" Sönmeden yurdumun üstünde tüten en son ocak")
print(" O benim milletimin yıldızıdır, parlayacak")
print(" O benimdir,o benim milletimindir ancak")
print("\n")
print("******* Öğrenci Bilgileri *******")
print("    Adı      : Mustafa Erhan     ")
print("    Soyadı   : Dönmez            ")
print("    Numarası : 999               ")
print("*********************************")
print("\n")
print('''Ali'nin Annesi "gel" dedi''' )
print("\n")
print("Ertan"*100)
print("\n")
print("Ertan\n"*10)
print("\n")